version: 1.0
language: node_js
node_js:
  - node
  - lts/*
before_script: npm i date-fns@~2.0.0
deploy:
  edge: true
  provider: npm
  email: "$NPM_EMAIL"
  api_key: "$NPM_TOKEN"
  on:
    branch: master
    node_js: node
